[package]
name = "save-the-planet"
version = "0.1.0"
authors = ["Jonathan <jogru0@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
bracket-terminal = "0.8.7"
crossterm = "0.27.0"
indexmap = "2.0.0"
ratatui = "0.22.0"
